# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pr:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.slnx'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: dotnet build solution
  inputs:
    command: 'build'
    configuration: '$(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: dotent pack QRCodeGeneratorApp.Helper.csproj
  inputs:
    command: 'pack'
    packagesToPack: '**/QRCodeGeneratorApp.Helper.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/custom-nuget-packages'
    versioningScheme: 'byBuildNumber'
      

- task: DotNetCoreCLI@2
  displayName: donet push custom nuget packages
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/custom-nuget-packages/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'c096b3b9-a525-4ae1-b0d5-2764415d837a/78d4438d-26e2-4ef4-b3c5-f432fb3ae273'

